export const categories = [
  'Browser Integration',
  'Colorschemes',
  'Code Runner',
  'Command Line',
  'Comment',
  'Completion',
  'Cursor Line',
  'Debugging',
  'Dependency Management',
  'Extras',
  'Formatting',
  'File Explorer',
  'Full Preconfigured',
  'Fuzzy Finder',
  'Game',
  'Git',
  'Guides',
  'Keybinding',
  'Indent',
  'LSP',
  'Misc',
  'Media',
  'Motion',
  'Mouse',
  'Note Taking',
  'Package Managers',
  'Personal Dotfiles',
  'Plugin Creation',
  'Project',
  'Quick Fix',
  'Search',
  'Session',
  'Scrolling',
  'Snippets',
  'Splits and Window',
  'Start Up',
  'Status Line',
  'Syntax',
  'Tabline',
  'Terminal Integration',
  'Test',
  'Tmux',
  'Utility',
  'Web Development',
]
